sim: dtmc.cpp eigenutil.cpp main.cpp
	g++ -g -Wall -I /usr/local/include/eigen-3.4.0 -std=c++17 main.cpp dtmc.cpp eigenutil.cpp -o sim  # Mac
	# g++ -g -Wall -std=c++17 -I "[absolute path to Eigen]" main.cpp dtmc.cpp eigenutil.cpp -o sim  # Windows
